### ISSUE TITLE
Key is not known in rets.

### ISSUE THREAD

**Issue by ramesh-bacancy** [estately/rets#221] opened 2019-12-17 07:35 UTC
Hi,
   I'm using the rets gem. I have done with rets mapping to my application. Now trying to fetching the images from MLS server. But I'm getting the issues like **(DMQL: Field 'ListingKey' is not known)** Please help me with this issue. I'm sharing the screenshots also please have a look at this.

![dmql1](https://user-images.githubusercontent.com/40857981/70974463-cee94500-20cd-11ea-93a7-93422c42fa0f.png)

![dmql2](https://user-images.githubusercontent.com/40857981/70974475-d7418000-20cd-11ea-83ca-80c63363b21c.png)

![dmql3](https://user-images.githubusercontent.com/40857981/70974484-ddcff780-20cd-11ea-8fca-96a803d4ee93.png)

Thanks.

**Comment by dougcole** [comment] 2019-12-17 17:26
It looks to me like none of the field names you are trying to use exist in the class you are searching. You need to find the correct field name to use for images, they should be in the metadata.

**Comment by dougcole** [comment] 2019-12-17 17:27
I'm closing this now, as it's not a bug in the rets gem. Hopefully that was enough to get you on the right path!

**Closed as completed by dougcole** 2019-12-17 17:27 UTC
